# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.3'

gem 'bootsnap', '>= 1.4.2', require: false
gem 'puma', '~> 3.11'
gem 'rails', '~> 6.0.0.rc1'

group :development do
  gem 'onkcop'
  gem 'rubocop', '0.67'
  # gem "rubocop-rails"
end

gem 'solrb'
gem 'zk'
